//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssWebApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedItem
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string Body { get; set; }
        public string Url { get; set; }
        public Nullable<int> FeedProvider_Id { get; set; }
    
        public virtual FeedProvider FeedProvider { get; set; }
    }
}
